name: Content Proposal From Writer
description: Propose a content idea
assignees: Theodore
body:
  - type: markdown
    attributes:
      value: |
        Due to the high volume of submissions, we are no longer accepting new articles at this time. Please choose from the existing articles labeled "Looking for Author.
