name: Write For Community Update
description: Due to the high volume of submissions, we are no longer accepting new articles at this time. Please choose from the existing articles labeled "Looking for Author."
assignees: Theodore
